run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - govet
#    - staticcheck
    - misspell
    - unconvert
    - usestdlibvars

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hstreamdb/hstreamdb-go)
#  staticcheck:
#    go: '1.21'